# OpenTelemetry Collector Development Configuration
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:
  memory_limiter:
    limit_mib: 512
  resource:
    attributes:
      - key: environment
        value: development
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  prometheusremotewrite:
    endpoint: "http://prometheus-dev:9090/api/v1/write"
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, prometheusremotewrite, logging]
  
  extensions: []
  
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: 0.0.0.0:8888